version: '3.7'
services:
  roc:
    image: $REGISTRY_URL/$PROJECT_NAME:test
    environment:
      - "APP_PROJECT=roc"
      - "APP_ENV=test"
    ports:
      - 9501:9501
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    networks:
      - roc_net
    configs:
      - source: roc_v1.0
        target: /.env
configs:
  roc_v1.0:
    file: ".env.example"
networks:
  roc_net:
    external: true
