on: [ push, pull_request ]
name: Test
jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }} Swoole ${{ matrix.swoole-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.0' ]
        swoole-version: [ 'v4.8.8', 'master' ]
      max-parallel: 5
    env:
      SW_VERSION: ${{ matrix.swoole-version }}
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
          extensions: pdo, pdo_mysql, redis
      - name: Setup Swoole
        run: |
          cd /tmp
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/${SW_VERSION}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/${PHP_VERSION}/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/${PHP_VERSION}/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Setup JSON RPC Server
        run: |
          cp .env.example .env
          docker build . -t roc
          docker run -p 9501:9501 --rm --name roc_server -d roc:latest
      - name: Show Environment
        run: |
          php -v
          php -m
          php -i
      - name: Run Test Cases
        run: |
          git clone https://github.com/limingxinleo/roc-client.git
          cd roc-client
          composer update -oW
          composer test

